// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POC_PremiumInterface.Models
{
    public partial class MappingBank
    {
        [Key]
        public int BankId { get; set; }
        [StringLength(255)]
        public string BankDetail { get; set; }
        [StringLength(20)]
        public string BankShortName { get; set; }
        [StringLength(20)]
        public string MappingCode { get; set; }
        [StringLength(255)]
        public string MappingDetail { get; set; }
        public string Remark { get; set; }
        public bool? IsActive { get; set; }
    }
}