// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POC_PremiumInterface.Models
{
    public partial class QueueType
    {
        [Key]
        public int QueueTypeId { get; set; }
        [StringLength(50)]
        public string QueueTypeDetail { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
    }
}