// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POC_PremiumInterface.Models
{
    public partial class Queue
    {
        [Key]
        public Guid QueueId { get; set; }
        public Guid QueueGroupId { get; set; }
        public int? QueueTypeId { get; set; }
        [StringLength(20)]
        public string QueueCode { get; set; }
        public int? FromBankId { get; set; }
        [StringLength(20)]
        public string FromAccountNo { get; set; }
        public int? ToBankId { get; set; }
        [StringLength(20)]
        public string ToAccountNo { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? Amount { get; set; }
        public int? QueuestatusId { get; set; }
        public string CancelRemark { get; set; }
        public DateTime? TransferDate { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }
        public bool? IsQueueClosed { get; set; }
        public DateTime? QueueClosedDate { get; set; }

        [ForeignKey(nameof(QueueTypeId))]
        [InverseProperty("Queues")]
        public virtual QueueType QueueType { get; set; }
    }
}