// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POC_PremiumInterface.Models
{
    public partial class ZPMType
    {
        public ZPMType()
        {
            ZPMTransactions = new HashSet<ZPMTransaction>();
        }

        [Key]
        public int ZPMTypeId { get; set; }
        [StringLength(6)]
        public string ZPMTypeCode { get; set; }
        [StringLength(50)]
        public string ZPMTypeDetail { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }

        [InverseProperty(nameof(ZPMTransaction.ZPMType))]
        public virtual ICollection<ZPMTransaction> ZPMTransactions { get; set; }
    }
}