// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POC_PremiumInterface.Models
{
    public partial class ZPMTransaction
    {
        [Key]
        public Guid ZPMTransactionId { get; set; }
        public int? ZPMTypeId { get; set; }
        public Guid? QueueId { get; set; }
        [StringLength(20)]
        public string BatchNo { get; set; }
        public int? ItemCount { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? Amount { get; set; }
        public int? TransactionStatusId { get; set; }
        public string ErrorMessage { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? DocumentDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        [StringLength(50)]
        public string RefFileName { get; set; }
        public bool? IsQueueTransfer { get; set; }

        [ForeignKey(nameof(ZPMTypeId))]
        [InverseProperty("ZPMTransactions")]
        public virtual ZPMType ZPMType { get; set; }
    }
}