// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MoviesAPI.Models
{
    public partial class Department
    {
        public Department()
        {
            People = new HashSet<Person>();
        }

        [Key]
        public int DepartmentId { get; set; }
        [StringLength(50)]
        public string DepartmentDetail { get; set; }

        [InverseProperty(nameof(Person.Department))]
        public virtual ICollection<Person> People { get; set; }
    }
}