// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MoviesAPI.Models
{
    public partial class Gender
    {
        public Gender()
        {
            People = new HashSet<Person>();
        }

        [Key]
        public int GenderId { get; set; }
        [StringLength(50)]
        public string GenderDetail { get; set; }

        [InverseProperty(nameof(Person.Gender))]
        public virtual ICollection<Person> People { get; set; }
    }
}