// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MoviesAPI.Models
{
    public partial class Movies
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        [StringLength(50)]
        public string Summary { get; set; }
        public bool InTheaters { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ReleaseDate { get; set; }
        public int PersonId { get; set; }
        public int GenresId { get; set; }

        [ForeignKey(nameof(GenresId))]
        [InverseProperty("Movies")]
        public virtual Genres Genres { get; set; }
        [ForeignKey(nameof(PersonId))]
        [InverseProperty("Movies")]
        public virtual Person Person { get; set; }

       
    }
}