// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MoviesAPI.Models
{
    public partial class Person
    {
        [Key]
        public int Id { get; set; }
        public int GenderId { get; set; }
        public int DepartmentId { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        public string Picture { get; set; }

        [ForeignKey(nameof(DepartmentId))]
        [InverseProperty("People")]
        public virtual Department Department { get; set; }
        [ForeignKey(nameof(GenderId))]
        [InverseProperty("People")]
        public virtual Gender Gender { get; set; }
    }
}